package com.fgiannesini.neuralnetwork.learningalgorithm;

public enum LearningAlgorithmType {

    GRADIENT_DESCENT_DERIVATION,
    GRADIENT_DESCENT_DERIVATION_MOMENTUM,
    GRADIENT_DESCENT_DERIVATION_RMS_STOP,
    GRADIENT_DESCENT_DERIVATION_ADAM_OPTIMISATION,

    GRADIENT_DESCENT,
    GRADIENT_DESCENT_MOMENTUM,
    GRADIENT_DESCENT_RMS_STOP,
    GRADIENT_DESCENT_ADAM_OPTIMISATION
}
